version: '2'

services:

  nginx:
    build: environment/nginx
    ports:
      - 8080:80
    volumes_from:
      - app

  app:
    command: "true"
    image: alpine:3.4
    volumes:
      - .:/var/www/app

  php:
    build: environment/php
    expose:
      - 9000
    volumes:
      - composer-cache:/composer/cache
    volumes_from:
      - app
    env_file:
      - ".env"

volumes:
  composer-cache:
    driver: local
