<!DOCTYPE html>
<html lang="pt-br">
<head>
<?php
$baseUrl = 'http://' . $_SERVER['HTTP_HOST'] . '/';
isset($folder) ? $folder = $folder : $folder = '';
isset($modulo) ? $modulo = ' | '.$modulo : $modulo = '';
isset($acao) ? $acao = ' | '.$acao : $acao = '';
?>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?php echo(getenv('SISTEM_NAME')); echo($modulo.$acao); ?></title>
    <link rel="shortcut icon" href="<?php echo($baseUrl); ?><?php echo(getenv('FAVICOM_PATH')); ?>">
    <!-- Bootstrap -->
    <link href="<?php echo($baseUrl); ?>vendors/bootstrap/dist/css/bootstrap.min.css?<?php echo(getenv('SISTEM_TAG')); ?>" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="<?php echo($baseUrl); ?>vendors/font-awesome/css/font-awesome.min.css?<?php echo(getenv('SISTEM_TAG')); ?>" rel="stylesheet">
    <!-- Animate.css -->
    <link href="<?php echo($baseUrl); ?>vendors/animate.css/animate.min.css?<?php echo(getenv('SISTEM_TAG')); ?>" rel="stylesheet">
    <!-- iCheck -->
    <link href="<?php echo($baseUrl); ?>vendors/iCheck/skins/flat/green.css?<?php echo(getenv('SISTEM_TAG')); ?>" rel="stylesheet">
    <!-- bootstrap-progressbar -->
    <link href="<?php echo($baseUrl); ?>vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css?<?php echo(getenv('SISTEM_TAG')); ?>" rel="stylesheet">
    <!-- Switchery -->
    <link href="<?php echo($baseUrl); ?>vendors/switchery/dist/switchery.min.css?<?php echo(getenv('SISTEM_TAG')); ?>" rel="stylesheet">
    <!-- NProgress -->
    <link href="<?php echo($baseUrl); ?>vendors/nprogress/nprogress.css?<?php echo(getenv('SISTEM_TAG')); ?>" rel="stylesheet">
    <?php
    if(isset($adicionalCss) && is_array($adicionalCss)) {
        foreach ($adicionalCss as $style) {
    ?><link href="<?php echo $baseUrl.$style ?>?<?php echo(getenv('SISTEM_TAG')); ?>" type="text/css" rel="stylesheet">
    <?php
        }
    } ?><!-- Custom Theme Style -->
    <link href="<?php echo($baseUrl); ?>build/css/custom.css?<?php echo(getenv('SISTEM_TAG')); ?>" rel="stylesheet">
    <!-- jQuery -->
    <script src="<?php echo($baseUrl); ?>vendors/jquery/dist/jquery.min.js?<?php echo(getenv('SISTEM_TAG')); ?>"></script>
    <!-- Bootstrap -->
    <script src="<?php echo($baseUrl); ?>vendors/bootstrap/dist/js/bootstrap.min.js?<?php echo(getenv('SISTEM_TAG')); ?>"></script>
</head>
<body class="nav-md">
<div id="preloader" style="display: none;">
    <div id="spinner">
        <i class="fa fa-refresh fa-spin fa-3x fa-fw"></i>
        <span class="sr-only">Loading...</span>
    </div>
</div>
<div class="container body">
    <div class="main_container">
        <!-- left navigation -->
        <div class="col-md-3 left_col">
            <div class="left_col scroll-view">
                <div class="navbar nav_title" style="border: 0;">
                    <a href="dashboard" class="site_title">
                        <img src="<?php echo($baseUrl); ?><?php echo(getenv('LOGO_IMAGE_PATH')); ?>" alt="<?php echo(getenv('SISTEM_NAME')); ?>">
                    </a>
                </div>
                <div class="clearfix"></div>
                <br />
                <!-- sidebar menu -->
                <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                    <div class="menu_section">
                        <h3><?php echo(getenv('SISTEM_NAME')); ?></h3>
                        <ul class="nav side-menu">
                            <li><a href="dashboard"><i class="fa fa-tachometer"></i> Dashboard</span></a></li>
                            <li id="menu-empresas"><a><i class="fa fa-building-o"></i> Empresa <span class="fa fa-chevron-down"></span></a>
                                <ul class="nav child_menu">
                                    <li><a href="empresa/cadastrar">Cadastro</a></li>
                                    <li><a href="empresa/listar">Listar/Pesquisar</a></li>
                                </ul>
                            </li>
                            <li><a><i class="fa fa-address-card"></i> Usuário <span class="fa fa-chevron-down"></span></a>
                                <ul class="nav child_menu">
                                    <li><a href="<?=$baseUrl?>usuario/cadastro">Cadastrar</a></li>
                                    <li><a href="<?=$baseUrl?>usuario/listar">Listar</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
                <!-- /sidebar menu -->
                <!-- /menu footer buttons -->
                <div class="sidebar-footer hidden-small">
                    <a data-toggle="tooltip" data-placement="top" title="Configurações">
                        <i class="fa fa-cog" aria-hidden="true"></i>
                    </a>
                    <a data-toggle="tooltip" data-placement="top" title="Suporte" >
                        <i class="fa fa-life-ring" aria-hidden="true"></i>
                    </a>
                    <a data-toggle="tooltip" data-placement="top" title="Ajuda">
                        <i class="fa fa-question-circle" aria-hidden="true"></i>
                    </a>
                    <a href="logout" data-toggle="tooltip" data-placement="top" title="Sair">
                        <i class="fa fa-sign-out" aria-hidden="true"></i>
                    </a>
                </div>
                <!-- /menu footer buttons -->
            </div>
        </div>
        <!-- /left navigation -->
        <!-- top navigation -->
        <div class="top_nav">
            <div class="nav_menu">
                <nav class="" role="navigation">
                    <div class="nav toggle">
                        <a id="menu_toggle"><i class="fa fa-bars"></i></a>
                    </div>
                    <ul class="nav navbar-nav navbar-right">
                        <li class="">
                            <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                                João Ninguém
                                <span class=" fa fa-angle-down"></span>
                            </a>
                            <ul class="dropdown-menu dropdown-usermenu pull-right">
                                <li><a href="javascript:;"><i class="fa fa-user pull-right"></i> Perfil</a></li>
                                <li><a href="javascript:;"><i class="fa fa-cog pull-right"></i><span>Configurações</span></a></li>
                                <li><a href="javascript:;"><i class="fa fa-life-ring pull-right"></i><span>Suporte</span></a></li>
                                <li><a href="javascript:;"><i class="fa fa-question-circle pull-right"></i>Ajuda</a></li>
                                <li><a href="logout"><i class="fa fa-sign-out pull-right"></i> Sair</a></li>
                            </ul>
                        </li>
                        <li role="presentation" class="dropdown">
                            <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown" aria-expanded="false">
                                <i class="fa fa-envelope-o"></i>
                                <span class="badge bg-green">1</span>
                            </a>
                            <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
                                <li>
                                    <a>
                                        <span>
                                            <span>Harry Janz</span>
                                                <span class="time">3 mins atrás</span>
                                            </span>
                                        <span class="message">
                                            Você tem uma fatura em atraso!
                                        </span>
                                    </a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
        <!-- /top navigation -->
        <!-- page content -->
        <div class="right_col" role="main">